name: Render-KeepAlive

# Permet le déclenchement manuel ET toutes les 14 minutes par cron
on:
  workflow_dispatch:
  schedule:
    - cron: "*/14 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Vérifier le code HTTP de l’app Render
        run: |
          echo "→ Envoi d’un HEAD vers l’URL…"
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://sentra-core-mem.onrender.com/)
          echo "  Code HTTP reçu : $HTTP_STATUS"
          if [[ "$HTTP_STATUS" != "200" ]]; then
            echo "‼️ Erreur : la racine ne renvoie pas 200 OK. (actuellement : $HTTP_STATUS)"
            exit 1
          fi
          echo "✅ Le service répond bien (200 OK)."
