name: ZSYNC Scheduler

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  zsync:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le repo
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Vérifier la présence du fichier
        run: ls scripts/zsync_scheduler.py

      - name: Exécuter le script ZSYNC
        run: python scripts/zsync_scheduler.py
